version: "2.0"

services:
  web:
    image: REPLACE_IMAGE
    env:
      - PORT=80
    expose:
      - port: 80
        as: 80
        accept: ["*"]
        to:
          - global: true

profiles:
  compute:
    web:
      resources:
        cpu:
          units: 0.5
        memory:
          size: 512Mi
        storage:
          size: 1Gi

deployment:
  web:
    profile: web
    count: 1
