name: Deploy to Akash

on:
  push:
    branches: [ "main" ]
  pull_request:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: 检出代码
      - name: Check out code
        uses: actions/checkout@v3

      # Step 2: 重试 Docker 登录
      - name: Docker Login
        run: |
          for i in {1..5}; do
            echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin && break || sleep 10;
          done

      # Step 3: 构建 Docker 镜像
      - name: Build Docker image
        run: |
          docker build -t my-app:${{ github.sha }} .
          docker tag my-app:${{ github.sha }} my-registry.com/my-app:${{ github.sha }}

      # Step 4: 推送 Docker 镜像
      - name: Push Docker image
        run: |
          docker push my-registry.com/my-app:${{ github.sha }}

      # Step 5: 部署到 Akash
      - name: Deploy to Akash
        env:
          AKASH_MNEMONIC: ${{ secrets.AKASH_MNEMONIC }}
          AKASH_KEY_NAME: ${{ secrets.AKASH_KEY_NAME }}
          AKASH_CHAIN_ID: ${{ secrets.AKASH_CHAIN_ID }}
          AKASH_NODE_URL: ${{ secrets.AKASH_NODE_URL }}
        run: |
          echo "$AKASH_MNEMONIC" | akash keys add $AKASH_KEY_NAME --recover --keyring-backend file --overwrite
          akash tx deployment create akash/deploy.yml \
            --from $AKASH_KEY_NAME \
            --chain-id $AKASH_CHAIN_ID \
            --node $AKASH_NODE_URL \
            --gas auto --gas-adjustment 1.25 \
            -y --keyring-backend file
