- name: Check Balance
  env:
    AKASH_KEY_NAME: ${{ secrets.AKASH_KEY_NAME }}
    KEYRING_PASSPHRASE: ${{ secrets.KEYRING_PASSPHRASE }}
    AKASH_CHAIN_ID: sandbox-01
    AKASH_NODE_URL: http://rpc.sandbox-01.aksh.pw:26657
  run: |
    # Debug the akash CLI installation
    if ! command -v akash &> /dev/null; then
      echo "Error: Akash CLI is not installed or not in PATH."
      exit 1
    fi

    # Verify the keyring contains the correct key
    akash keys list --keyring-backend file

    # Write the expect script to retrieve the address
    echo '#!/usr/bin/expect -f
    log_user 1
    spawn akash keys show "$env(AKASH_KEY_NAME)" -a --keyring-backend file
    expect "Enter keyring passphrase:"
    send "$env(KEYRING_PASSPHRASE)\r"
    expect {
      -re {^(akash1[a-z0-9]+)$} {
        set address $expect_out(1,string)
        send_user "$address\n"
      }
      timeout {
        send_user "Error: Timed out waiting for response.\n"
        exit 1
      }
    }
    expect eof' > get_address.exp

    chmod +x get_address.exp
    ADDR=$(./get_address.exp)

    # Verify address retrieval
    if [ -z "$ADDR" ]; then
      echo "Error: Unable to retrieve wallet address."
      exit 1
    fi
    echo "Your wallet address is: $ADDR"

    # Query balance
    echo "Querying bank balances on $AKASH_CHAIN_ID..."
    akash query bank balances "$ADDR" --node "$AKASH_NODE_URL"
