name: Deploy to Akash

on:
  push:
    branches: [ "main" ]
  pull_request:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out the code
      - name: Check out code
        uses: actions/checkout@v3

      # Step 2: Install Akash CLI
      - name: Install Akash CLI
        run: |
          curl -sSL https://github.com/ovrclk/akash/releases/latest/download/akash_$(uname -s)_$(uname -m).zip -o akash.zip
          mkdir -p akash-cli
          unzip akash.zip -d akash-cli
          sudo mv akash-cli/akash /usr/local/bin/akash
          akash version

      # Step 3: Recover Akash Wallet
      - name: Recover Akash Wallet
        env:
          AKASH_MNEMONIC: ${{ secrets.AKASH_MNEMONIC }}
          AKASH_KEY_NAME: ${{ secrets.AKASH_KEY_NAME }}
          KEYRING_PASSPHRASE: ${{ secrets.KEYRING_PASSPHRASE }}
        run: |
          sudo apt-get update && sudo apt-get install -y expect
          echo "
          spawn akash keys add \"$AKASH_KEY_NAME\" --recover --keyring-backend file
          expect \"Enter your bip39 mnemonic:\"
          send \"$AKASH_MNEMONIC\\r\"
          expect \"Enter keyring passphrase:\"
          send \"$KEYRING_PASSPHRASE\\r\"
          expect \"Re-enter keyring passphrase:\"
          send \"$KEYRING_PASSPHRASE\\r\"
          expect eof
          " > recovery-script.exp
          expect recovery-script.exp

      # Step 4: Debug Keys
      - name: Debug Keys
        run: |
          echo "Listing all keys in Akash CLI:"
          akash keys list

      # Step 5: Deploy to Akash
      - name: Deploy to Akash
        env:
          AKASH_KEY_NAME: ${{ secrets.AKASH_KEY_NAME }}
          AKASH_CHAIN_ID: ${{ secrets.AKASH_CHAIN_ID }}
          AKASH_NODE_URL: ${{ secrets.AKASH_NODE_URL }}
          KEYRING_PASSPHRASE: ${{ secrets.KEYRING_PASSPHRASE }}
        run: |
          echo "$KEYRING_PASSPHRASE" | akash tx deployment create deploy.yml \
            --from "$AKASH_KEY_NAME" \
            --chain-id "$AKASH_CHAIN_ID" \
            --node "$AKASH_NODE_URL" \
            --gas auto --gas-adjustment 1.25 \
            -y --keyring-backend file --sign-mode direct
