name: Deploy to Akash Node

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. 检出代码
      - name: Check out code
        uses: actions/checkout@v3

      # 2. 配置 Akash CLI 使用远程节点
      - name: Configure Akash CLI
        run: |
          mkdir -p ~/.akash
          echo "node = 'https://rpc.akashnet.net:443'" > ~/.akash/config.toml
          echo "chain-id = 'akashnet-2'" >> ~/.akash/config.toml
          echo "broadcast-mode = 'block'" >> ~/.akash/config.toml
          echo "keyring-backend = 'file'" >> ~/.akash/config.toml
          echo "Akash CLI configured to use remote node."

      # 3. 创建新钱包（如需要）
      - name: Create Akash Wallet
        run: |
          echo "${{ secrets.AKASH_KEY_PASSPHRASE }}" | akash keys add "${{ secrets.AKASH_KEY_NAME }}" --keyring-backend file
          ADDR=$(echo "${{ secrets.AKASH_KEY_PASSPHRASE }}" | akash keys show "${{ secrets.AKASH_KEY_NAME }}" -a --keyring-backend file)
          echo "Wallet Address: $ADDR"
          echo "AKASH_ADDRESS=$ADDR" >> $GITHUB_ENV

      # 4. 生成 SDL 文件
      - name: Generate SDL File
        run: |
          cat <<EOF > deployment.yaml
          version: "2.0"

          services:
            web:
              image: "${{ secrets.DOCKER_USERNAME }}/my-app:latest"
              expose:
                - port: 80
                  as: 80
                  to:
                    - global: true

          profiles:
            compute:
              basic:
                resources:
                  cpu:
                    units: 0.5
                  memory:
                    size: 512Mi
                  storage:
                    size: 1Gi
            placement:
              basic:
                attributes: {}
                signedBy:
                  anyOf: []
                pricing:
                  web:
                    denom: uakt
                    amount: 1000

          deployment:
            web:
              profile: basic
              count: 1
          EOF

      # 5. 创建部署
      - name: Create Deployment
        run: |
          echo "${{ secrets.AKASH_KEY_PASSPHRASE }}" | akash tx deployment create deployment.yaml \
          --from "${{ secrets.AKASH_KEY_NAME }}" \
          --deposit "5000000uakt" \
          --yes \
          --keyring-backend file \
          --sign-mode direct
          echo "Deployment created!"

      # 6. 验证部署状态
      - name: Verify Deployment
        run: |
          ADDR=$AKASH_ADDRESS
          DSEQ=$(akash query deployment list --owner "$ADDR" --state active -o json | jq -r '.deployments[-1].deployment.deployment_id.dseq')
          echo "Deployment Sequence: $DSEQ"
          echo "Deployment verified!"
