name: Create Akash Key

on:
  workflow_dispatch:

jobs:
  create-akash-key:
    runs-on: ubuntu-latest

    steps:
      # 安装 Akash CLI
      - name: Install Akash CLI
        run: |
          set -eux
          DOWNLOAD_URL="https://github.com/ovrclk/akash/releases/download/v1.0.0-rc10/akash_1.0.0-rc10_linux_amd64.zip"
          curl -sSL "$DOWNLOAD_URL" -o akash.zip
          mkdir -p akash-cli
          unzip akash.zip -d akash-cli
          sudo mv akash-cli/akash /usr/local/bin/akash
          sudo chmod +x /usr/local/bin/akash
          akash version

      # 创建新密钥并记录信息
      - name: Create new Akash key
        env:
          NEW_KEY_NAME: my-new-key
          KEYRING_PASSPHRASE: "your-secure-password"  # 可以在这里设置安全密码
        run: |
          set -eux
          echo "创建新的密钥: $NEW_KEY_NAME"

          # 动态创建密钥
          echo "$KEYRING_PASSPHRASE" | akash keys add "$NEW_KEY_NAME" --keyring-backend file > new-key-info.txt

          echo "密钥已创建，保存密钥信息到文件 new-key-info.txt"
          cat new-key-info.txt

          # 提取地址
          KEY_ADDRESS=$(grep -oP '(?<=address:\s).*' new-key-info.txt)
          echo "地址: $KEY_ADDRESS"

          # 提取助记词
          MNEMONIC=$(grep -oP '(?<=mnemonic:\s).*' new-key-info.txt)
          echo "助记词: $MNEMONIC"

      # 保存密钥信息（供后续操作使用）
      - name: Output key information
        run: |
          echo "将密钥地址和助记词输出到控制台供手动记录："
          echo "::set-output name=key_address::$KEY_ADDRESS"
          echo "::set-output name=mnemonic::$MNEMONIC"
