#!/usr/bin/expect -f
set timeout 20
log_user 1
exp_internal 1   ;# 若想查看更详细的 Expect 调试信息可以保留

if { [info exists ::env(AKASH_KEY_NAME)] == 0 || [info exists ::env(KEYRING_PASSPHRASE)] == 0 } {
    puts "错误：环境变量 AKASH_KEY_NAME 或 KEYRING_PASSPHRASE 未设置。"
    exit 1
}

spawn akash keys show "$::env(AKASH_KEY_NAME)" -a --keyring-backend file
expect {
    -re {Enter keyring passphrase.*} {
        send "$::env(KEYRING_PASSPHRASE)\r"
    }
    eof {
        puts "错误：spawn 命令未成功执行。(可能找不到 akash？)"
        exit 1
    }
    timeout {
        puts "错误：spawn 命令超时。"
        exit 1
    }
}

expect {
    -re {^(akash1[a-z0-9]+)$} {
        set address $expect_out(1,string)
        send_user "$address\n"
    }
    timeout {
        puts "错误：未能捕获钱包地址。"
        exit 1
    }
}

expect eof
