name: Register and Deploy Akash Key

on:
  workflow_dispatch:

jobs:
  register-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # 第1步：安装 Akash CLI
      - name: Install Akash CLI
        run: |
          set -eux
          DOWNLOAD_URL="https://github.com/ovrclk/akash/releases/download/v1.0.0-rc10/akash_1.0.0-rc10_linux_amd64.zip"
          echo "Downloading Akash CLI from $DOWNLOAD_URL"
          curl -sSL "$DOWNLOAD_URL" -o akash.zip
          mkdir -p akash-cli
          unzip akash.zip -d akash-cli
          sudo mv akash-cli/akash /usr/local/bin/akash
          sudo chmod +x /usr/local/bin/akash
          echo "Akash CLI installed successfully:"
          akash version

      # 第2步：创建新的密钥
      - name: Register a new Akash key
        env:
          NEW_KEY_NAME: my-new-key
          KEYRING_PASSPHRASE: "your-secure-password"
        run: |
          set -eux
          echo "Creating a new Akash key: $NEW_KEY_NAME"
          echo "$KEYRING_PASSPHRASE" | akash keys add "$NEW_KEY_NAME" --keyring-backend file > new-key-info.txt

          echo "New key created successfully. Saving key information to new-key-info.txt."
          cat new-key-info.txt

          # 提取密钥地址
          KEY_ADDRESS=$(grep -oP '(?<=address:\s).*' new-key-info.txt)
          echo "Key address: $KEY_ADDRESS"

          # 提取助记词
          MNEMONIC=$(grep -oP '(?<=mnemonic:\s).*' new-key-info.txt)
          echo "Mnemonic: $MNEMONIC"

      # 第3步：传递密钥信息给贾维斯
      - name: Submit key information to Jarvis
        env:
          NEW_KEY_NAME: my-new-key
          KEY_ADDRESS: ${{ steps.register-a-new-akash-key.outputs.key_address }}
          MNEMONIC: ${{ steps.register-a-new-akash-key.outputs.mnemonic }}
        run: |
          set -eux
          echo "Sending key information to Jarvis..."
          curl -X POST -H "Content-Type: application/json" \
            -d '{"key_name": "'"$NEW_KEY_NAME"'", "key_address": "'"$KEY_ADDRESS"'", "mnemonic": "'"$MNEMONIC"'"}' \
            http://jarvis.internal/submit-key
          echo "Key information successfully submitted to Jarvis."

      # 第4步：部署
      - name: Deploy using new key
        env:
          AKASH_KEY_NAME: my-new-key
          KEYRING_PASSPHRASE: "your-secure-password"
        run: |
          set -eux
          echo "Deploying to Akash using the new key..."
          # 部署的具体逻辑根据需求自定义
          echo "Deployment successful!"
