name: Deploy to Akash Node

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. 检出代码
      - name: Check out code
        uses: actions/checkout@v3

      # 2. 安装 Akash CLI
      - name: Install Akash CLI
        run: |
          sudo apt-get update
          sudo apt-get install -y unzip jq
          DOWNLOAD_URL="https://github.com/ovrclk/akash/releases/download/v1.0.0-rc10/akash_1.0.0-rc10_linux_amd64.zip"
          curl -sSL "$DOWNLOAD_URL" -o akash.zip
          unzip akash.zip -d akash-cli
          sudo mv akash-cli/akash /usr/local/bin/akash
          sudo chmod +x /usr/local/bin/akash
          echo "Akash CLI installed successfully."

      # 3. 配置 Akash CLI 使用远程节点
      - name: Configure Akash CLI
        run: |
          mkdir -p ~/.akash
          echo "node = 'https://rpc.akashnet.net:443'" > ~/.akash/config.toml
          echo "chain-id = 'akashnet-2'" >> ~/.akash/config.toml
          echo "broadcast-mode = 'block'" >> ~/.akash/config.toml
          echo "keyring-backend = 'file'" >> ~/.akash/config.toml
          echo "Akash CLI configured to use remote node."

      # 4. 创建新的 Akash 钱包
      - name: Create New Akash Wallet
        run: |
          echo "Creating a new Akash wallet..."
          NEW_WALLET_NAME="new-akash-wallet"
          (echo "qq112233"; echo "qq112233") | akash keys add "$NEW_WALLET_NAME" --keyring-backend file
          ADDR=$( (echo "qq112233") | akash keys show "$NEW_WALLET_NAME" -a --keyring-backend file )
          echo "Wallet Address: $ADDR"
          echo "AKASH_KEY_NAME=$NEW_WALLET_NAME" >> $GITHUB_ENV
          echo "AKASH_ADDRESS=$ADDR" >> $GITHUB_ENV

      # 5. 验证钱包是否正确创建
      - name: Verify Akash Wallet
        run: |
          akash keys list --keyring-backend file
          echo "Wallet Address: $AKASH_ADDRESS"

      # 6. 生成 SDL 文件 (deployment.yaml)
      - name: Generate SDL File
        run: |
          cat <<EOF > deployment.yaml
          version: "2.0"

          services:
            web:
              image: "${{ secrets.DOCKER_USERNAME }}/my-app:latest"
              expose:
                - port: 80
                  as: 80
                  to:
                    - global: true

          profiles:
            compute:
              basic:
                resources:
                  cpu:
                    units: 0.5
                  memory:
                    size: 512Mi
                  storage:
                    size: 1Gi
            placement:
              basic:
                attributes: {}
                signedBy:
                  anyOf: []
                pricing:
                  web:
                    denom: uakt
                    amount: 1000

          deployment:
            web:
              profile: basic
              count: 1
          EOF

      # 7. 创建部署
      - name: Create Deployment
        run: |
          echo "Creating deployment on Akash..."
          echo "qq112233" | akash tx deployment create deployment.yaml \
            --from "$AKASH_KEY_NAME" \
            --deposit "5000000uakt" \
            --yes \
            --keyring-backend file \
            --sign-mode direct
          echo "Deployment created!"

      # 8. 验证部署状态
      - name: Verify Deployment
        run: |
          DSEQ=$(akash query deployment list --owner "$AKASH_ADDRESS" --state active -o json | jq -r '.deployments[-1].deployment.deployment_id.dseq')
          echo "Deployment Sequence: $DSEQ"
          echo "Deployment verified!"
