name: Deploy to Akash

on:
  push:
    branches: [ "main" ]
  pull_request:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Log in to Docker registry
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin

      - name: Build Docker image
        run: |
          docker build -t my-app:${{ github.sha }} .
          docker tag my-app:${{ github.sha }} my-registry.com/my-app:${{ github.sha }}

      - name: Push Docker image
        run: |
          docker push my-registry.com/my-app:${{ github.sha }}

      - name: Generate SDL
        run: |
          sed "s|REPLACE_IMAGE|my-registry.com/my-app:${{ github.sha }}|g" akash/deploy-template.yml > akash/deploy.yml

      - name: Deploy to Akash
        env:
          AKASH_MNEMONIC: ${{ secrets.AKASH_MNEMONIC }}
          AKASH_KEY_NAME: ${{ secrets.AKASH_KEY_NAME }}
          AKASH_CHAIN_ID: ${{ secrets.AKASH_CHAIN_ID }}
          AKASH_NODE_URL: ${{ secrets.AKASH_NODE_URL }}
        run: |
          echo "$AKASH_MNEMONIC" | akash keys add $AKASH_KEY_NAME --recover --keyring-backend file --overwrite
          akash tx deployment create akash/deploy.yml \
            --from $AKASH_KEY_NAME \
            --chain-id $AKASH_CHAIN_ID \
            --node $AKASH_NODE_URL \
            --gas auto --gas-adjustment 1.25 \
            -y --keyring-backend file
          akash query deployment get <deployment-id> --output json
