name: Deploy to Akash

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    env:
      DOCKER_IMAGE_NAME: "your-org/your-image"
      AKASH_KEY_NAME: "botkey"
      AKASH_NODE: "https://raw.raw.network:26657"
      AKASH_CHAIN_ID: "akashnet-2"
      DEPLOYMENT_NAME: "my-jarvis-bot"

    steps:
      # 1) 检出代码
      - name: Check out code
        uses: actions/checkout@v3

      # 2) 登录 Docker 仓库
      - name: Log in to Docker Registry
        run: |
          echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      # 3) 构建 Docker 镜像
      - name: Build Docker Image
        run: |
          docker build -t ${DOCKER_IMAGE_NAME}:latest .

      # 4) 推送 Docker 镜像
      - name: Push Docker Image
        run: |
          docker push ${DOCKER_IMAGE_NAME}:latest
