name: Minimal Working Workflow

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # 第1步：可选，如果你的工作流需要访问仓库代码，就保留
      - name: Check out code
        uses: actions/checkout@v3

      # 第2步：一个简单的 Echo 步骤，证明工作流已成功运行
      - name: Print a message
        run: echo "Hello from GitHub Actions! The workflow is working fine."
