name: Deploy to Akash

on:
  push:
    branches: [ "main" ]
  pull_request:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: 检出代码
      - name: Check out code
        uses: actions/checkout@v3

      # Step 2: (可选) 调试文件路径
      - name: Debug File Path
        run: |
          echo "Current working directory: $(pwd)"
          echo "Listing files in the current directory:"
          ls -R

      # Step 3: 安装 Akash CLI
      - name: Install Akash CLI
        run: |
          # 下载并解压 akash CLI
          curl -sSL https://github.com/ovrclk/akash/releases/download/v1.0.0-rc10/akash_1.0.0-rc10_linux_amd64.zip -o akash.zip
          if [ ! -s akash.zip ]; then
              echo "Download failed or file is empty."
              exit 1
          fi
          mkdir -p akash-cli
          unzip akash.zip -d akash-cli
          sudo mv akash-cli/akash /usr/local/bin/akash
          sudo chmod +x /usr/local/bin/akash

          # 验证安装是否成功
          akash version

      # Step 4: 恢复 Akash 钱包
      - name: Recover Akash Wallet
        env:
          AKASH_MNEMONIC: ${{ secrets.AKASH_MNEMONIC }}
          AKASH_KEY_NAME: ${{ secrets.AKASH_KEY_NAME }}
          KEYRING_PASSPHRASE: ${{ secrets.KEYRING_PASSPHRASE }}
        run: |
          sudo apt-get update && sudo apt-get install -y expect
          
          # 验证环境变量
          if [ -z "$AKASH_MNEMONIC" ] || [ -z "$AKASH_KEY_NAME" ] || [ -z "$KEYRING_PASSPHRASE" ]; then
            echo "Error: One or more required environment variables (AKASH_MNEMONIC, AKASH_KEY_NAME, KEYRING_PASSPHRASE) are missing."
            exit 1
          fi

          # 用 expect 自动输入助记词 + keyring 密码
          echo "
          spawn akash keys add \"$AKASH_KEY_NAME\" --recover --keyring-backend file
          expect \"Enter your bip39 mnemonic:\"
          send \"$AKASH_MNEMONIC\\r\"
          expect \"Enter keyring passphrase:\"
          send \"$KEYRING_PASSPHRASE\\r\"
          expect \"Re-enter keyring passphrase:\"
          send \"$KEYRING_PASSPHRASE\\r\"
          expect eof
          " > recovery-script.exp

          expect recovery-script.exp
          rm -f recovery-script.exp

      # Step 5: 调试密钥
      - name: Debug Keys
        run: |
          echo "Listing all keys in Akash CLI:"
          akash keys list

      # Step 6: 部署到 Akash（使用 HTTPS RPC）
      - name: Deploy to Akash
        env:
          AKASH_KEY_NAME: ${{ secrets.AKASH_KEY_NAME }}
          AKASH_CHAIN_ID: akashnet-2
          AKASH_NODE_URL: https://akash-rpc.polkachu.com
          KEYRING_PASSPHRASE: ${{ secrets.KEYRING_PASSPHRASE }}
        run: |
          # 1) 检查必要环境变量
          if [ -z "$AKASH_KEY_NAME" ] || [ -z "$AKASH_CHAIN_ID" ] || [ -z "$KEYRING_PASSPHRASE" ]; then
            echo "Error: One or more required environment variables (AKASH_KEY_NAME, AKASH_CHAIN_ID, KEYRING_PASSPHRASE) are missing."
            exit 1
          fi

          # 2) 检查部署文件
          if [ ! -f deploy.yml ]; then
            echo "Error: deploy.yml not found!"
            exit 1
          fi

          # 3) 可选：测试一下节点是否返回 JSON
          echo "Testing connectivity to $AKASH_NODE_URL..."
          curl --fail --max-time 10 "$AKASH_NODE_URL/status" || true

          # 4) 发起部署交易
          echo "$KEYRING_PASSPHRASE" | akash tx deployment create deploy.yml \
            --from "$AKASH_KEY_NAME" \
            --chain-id "$AKASH_CHAIN_ID" \
            --node "$AKASH_NODE_URL" \
            --gas auto --gas-adjustment 1.25 \
            -y --keyring-backend file --sign-mode direct
