name: Deploy to Akash

on:
  push:
    branches: [ "main" ]
  pull_request:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Docker Login
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build Docker image
        run: |
          docker build -t q18621281648/my-app:latest .

      - name: Push Docker image
        run: |
          docker push q18621281648/my-app:latest

      - name: Install Akash CLI
        run: |
          curl -sSL https://akash.network/install > install-akash.sh
          chmod +x install-akash.sh
          ./install-akash.sh

      - name: Deploy to Akash
        env:
          AKASH_MNEMONIC: ${{ secrets.AKASH_MNEMONIC }}
          AKASH_KEY_NAME: ${{ secrets.AKASH_KEY_NAME }}
          AKASH_CHAIN_ID: ${{ secrets.AKASH_CHAIN_ID }}
          AKASH_NODE_URL: ${{ secrets.AKASH_NODE_URL }}
        run: |
          echo "$AKASH_MNEMONIC" | akash keys add $AKASH_KEY_NAME --recover --keyring-backend file --overwrite
          akash tx deployment create akash/deploy.yml \
            --from $AKASH_KEY_NAME \
            --chain-id $AKASH_CHAIN_ID \
            --node $AKASH_NODE_URL \
            --gas auto --gas-adjustment 1.25 \
            -y --keyring-backend file
