- name: Deploy to Akash
  env:
    AKASH_MNEMONIC: ${{ secrets.AKASH_MNEMONIC }}
    AKASH_KEY_NAME: ${{ secrets.AKASH_KEY_NAME }}
    AKASH_CHAIN_ID: ${{ secrets.AKASH_CHAIN_ID }}
    AKASH_NODE_URL: ${{ secrets.AKASH_NODE_URL }}
  run: |
    echo "$AKASH_MNEMONIC" | akash keys add $AKASH_KEY_NAME --recover --keyring-backend file --no-passphrase
    akash tx deployment create akash/deploy.yml \
      --from $AKASH_KEY_NAME \
      --chain-id $AKASH_CHAIN_ID \
      --node $AKASH_NODE_URL \
      --gas auto --gas-adjustment 1.25 \
      -y --keyring-backend file
