name: Deploy to Akash Testnet

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build-and-deploy:
    runs-on: ubuntu-22.04

    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y expect yamllint

      - name: Install Akash CLI
        run: |
          set -eux
          DOWNLOAD_URL="https://github.com/ovrclk/akash/releases/download/v1.0.0-rc10/akash_1.0.0-rc10_linux_amd64.zip"
          echo "Downloading Akash CLI from $DOWNLOAD_URL"
          curl -sSL "$DOWNLOAD_URL" -o akash.zip
          mkdir -p akash-cli
          unzip akash.zip -d akash-cli
          sudo mv akash-cli/akash /usr/local/bin/akash
          sudo chmod +x /usr/local/bin/akash
          akash version

      - name: Validate environment variables
        env:
          AKASH_KEY_NAME: ${{ secrets.AKASH_KEY_NAME }}
          KEYRING_PASSPHRASE: ${{ secrets.KEYRING_PASSPHRASE }}
          AKASH_MNEMONIC: ${{ secrets.AKASH_MNEMONIC }}
        run: |
          set -eux
          echo "AKASH_KEY_NAME: $AKASH_KEY_NAME"
          echo "KEYRING_PASSPHRASE: ${#KEYRING_PASSPHRASE} characters (隐藏实际值)"
          echo "AKASH_MNEMONIC: ${#AKASH_MNEMONIC} characters (隐藏实际值)"

      - name: Import key from mnemonic
        env:
          AKASH_KEY_NAME: ${{ secrets.AKASH_KEY_NAME }}
          KEYRING_PASSPHRASE: ${{ secrets.KEYRING_PASSPHRASE }}
          AKASH_MNEMONIC: ${{ secrets.AKASH_MNEMONIC }}
        run: |
          set -eux
          CLEANED_MNEMONIC=$(echo "$AKASH_MNEMONIC" | tr -s ' ' | tr -d '\n')
          WORD_COUNT=$(echo "$CLEANED_MNEMONIC" | wc -w)
          if [ "$WORD_COUNT" -ne 24 ]; then
            echo "错误：助记词的单词数量不正确 (当前数量: $WORD_COUNT)"
            exit 1
          fi
          (echo "$KEYRING_PASSPHRASE"; echo "$KEYRING_PASSPHRASE"; echo "$CLEANED_MNEMONIC") \
            | akash keys add "$AKASH_KEY_NAME" --recover --keyring-backend file
          echo "密钥导入成功！"
