name: Register Kubernetes Credentials

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  register-and-store:
    runs-on: ubuntu-latest

    steps:
      # 1) 检出代码
      - name: Check out code
        uses: actions/checkout@v3

      # 2) 设置 kubeconfig 文件（用于连接到 Kubernetes 集群）
      - name: Set up kubeconfig
        run: |
          mkdir -p $HOME/.kube
          echo "${{ secrets.KUBECONFIG_CONTENT }}" > $HOME/.kube/config
          chmod 600 $HOME/.kube/config

      # 3) 测试 Kubernetes 连接
      - name: Test Kubernetes Connection
        run: |
          kubectl cluster-info
          kubectl get nodes

      # 4) 生成新账号密码密钥
      - name: Generate Kubernetes Secrets
        id: generate-secrets
        run: |
          # 设置新账号和密码
          NEW_USERNAME="new-kube-user"
          NEW_PASSWORD=$(openssl rand -base64 12)  # 生成随机密码
          NEW_SECRET_NAME="kube-user-secret"

          # 创建 Kubernetes 密钥
          kubectl create secret generic $NEW_SECRET_NAME \
            --from-literal=username=$NEW_USERNAME \
            --from-literal=password=$NEW_PASSWORD \
            -n default --dry-run=client -o yaml | kubectl apply -f -

          # 输出信息到环境变量
          echo "NEW_USERNAME=$NEW_USERNAME" >> $GITHUB_ENV
          echo "NEW_PASSWORD=$NEW_PASSWORD" >> $GITHUB_ENV
          echo "NEW_SECRET_NAME=$NEW_SECRET_NAME" >> $GITHUB_ENV
          echo "Kubernetes secret $NEW_SECRET_NAME created successfully."

      # 5) 验证密钥是否成功创建
      - name: Verify Secret Creation
        run: |
          kubectl get secret $NEW_SECRET_NAME -o yaml

      # 6) 记录账号密码密钥（提供给贾维斯）
      - name: Record Credentials for Jarvis
        run: |
          # 创建记录文件
          echo "Kubernetes Credentials for Jarvis:" > kube_credentials.txt
          echo "Username: $NEW_USERNAME" >> kube_credentials.txt
          echo "Password: $NEW_PASSWORD" >> kube_credentials.txt
          echo "Secret Name: $NEW_SECRET_NAME" >> kube_credentials.txt

      # 7) 将密钥记录上传为 Artifact
      - name: Upload Credentials Artifact
        uses: actions/upload-artifact@v3
        with:
          name: kube-credentials
          path: kube_credentials.txt
