name: Minimal Working Workflow

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # 第1步：检出代码（可选，只有在需要访问仓库代码时保留）
      - name: Check out code
        uses: actions/checkout@v3

      # 第2步：安装 Akash CLI（v1.0.0-rc10）
      - name: Install Akash CLI
        run: |
          sudo apt-get update
          sudo apt-get install -y unzip
          DOWNLOAD_URL="https://github.com/ovrclk/akash/releases/download/v1.0.0-rc10/akash_1.0.0-rc10_linux_amd64.zip"
          echo "Downloading Akash CLI from $DOWNLOAD_URL"
          curl -sSL "$DOWNLOAD_URL" -o akash.zip
          unzip akash.zip -d akash-cli
          sudo mv akash-cli/akash /usr/local/bin/akash
          sudo chmod +x /usr/local/bin/akash
          echo "Akash CLI installed successfully:"
          akash version

      # 第3步：注册一个 Akash 钱包
      - name: Register Akash Wallet
        env:
          KEY_NAME: newkey
          KEY_PASSPHRASE: "qq112233"
        run: |
          echo "Creating a new Akash wallet..."
          (echo "$KEY_PASSPHRASE"; echo "$KEY_PASSPHRASE") | akash keys add "$KEY_NAME" --keyring-backend file
          ADDR=$( (echo "$KEY_PASSPHRASE") | akash keys show "$KEY_NAME" -a --keyring-backend file )
          echo "Wallet registered successfully!"
          echo "Wallet Name: $KEY_NAME"
          echo "Wallet Address: $ADDR"
